"""initial schema

Revision ID: 70084f4531ae
Revises: 
Create Date: 2026-08-11 12:29:17.349099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70084f4531ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_set_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['script_set_id'], ['script_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objections_script_set_id'), 'objections', ['script_set_id'], unique=False)
    op.create_table('script_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_set_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('statement_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('allow_skip', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['script_set_id'], ['script_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_steps_script_set_id'), 'script_steps', ['script_set_id'], unique=False)
    op.create_table('objection_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objection_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['objection_id'], ['objections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objection_questions_objection_id'), 'objection_questions', ['objection_id'], unique=False)
    op.create_table('rebuttals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objection_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['objection_id'], ['objections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rebuttals_objection_id'), 'rebuttals', ['objection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rebuttals_objection_id'), table_name='rebuttals')
    op.drop_table('rebuttals')
    op.drop_index(op.f('ix_objection_questions_objection_id'), table_name='objection_questions')
    op.drop_table('objection_questions')
    op.drop_index(op.f('ix_script_steps_script_set_id'), table_name='script_steps')
    op.drop_table('script_steps')
    op.drop_index(op.f('ix_objections_script_set_id'), table_name='objections')
    op.drop_table('objections')
    op.drop_table('script_sets')
    # ### end Alembic commands ###
